Todo.create!(title: 'grocery shopping', description: 'pickles, eggs, red onion', is_done: true, due_date: '2016-10-10')
Todo.create!(title: 'wash the car', description: 'wash the car')
Todo.create!(title: 'register for school', description: 'Register for Rails High School', is_done: true)
Todo.create!(title: 'check engine light', description: 'The check engine light is on in the Tacoma', due_date: '2002-02-02')
Todo.create!(title: 'dog groomers', description: 'Take Pinky and Redford to the groomers')